words_list = [
['action','activity','actually','agent','ago','agree','approach',
'baby','behind','believe','benefit', 'blunt',
'charger', 'cheerleader', 'cog','company','compare',
'darts', 'dawn', 'dent', 'dimple', 'ditch',
'ebony', 'elephant', 
'feast', 'fiddle', 'fizz', 
'hedge','hose', 
'intern', 
'kangaroo', 'kitchen', 'knife', 
'monkey', 'mosquito', 
'plank', 'popsicle', 'prayer', 
'ray', 'ring', 
'saddle', 'seashell', 'seesaw', 'shovel', 
'tail', 'toothbrush', 'turtle', 
'whisper'],

['applause', 'application', 
'beanstalk', 'billboard', 'blossom', 'blueprint', 'booth', 'brainstorm', 
'capitalism','cardboard','culture','cuticle',
'director','discover','discuss','discussion','disease',
'economy','edge','education','election','employee','escalator', 
'feudalism', 'flannel', 'forever','fortnight', 'freight', 'fringe', 
'handwriting', 'hatch', 'humidifier', 'hopscotch', 
'inconceivable', 'irrational','individual','industry','information',
'midsummer','military','million', 
'population', 'publisher','participant', 
'riddle', 'recognize','relationship','religious',
'scoundrel', 'sequins', 'sheriff', 'shrink', 'skating', 'spool', 'squint', 
'throughout','tiptop', 'twitterpated', 
'whiplash'],

['affix', 'askew', 'avenue', 'awkward', 'axiom', 'azure', 
'bagpipes', 'bandwagon', 'banjo', 'bayou', 'beekeeper', 'blitz', 'blizzard', 'boggle', 'bookworm', 'boxcar', 'boxful', 
'croquet', 'crypt', 
'disavow', 'dizzying', 'duplex', 'dwarves', 
'embezzle', 'equip', 'espionage', 'environment', 'exodus', 
'gizmo', 'glowworm', 'glyph', 'gnarly', 'gnostic', 'gossip', 'grogginess', 
'haiku', 'haphazard', 'hyphen', 
'iatrogenic', 'icebox', 'injury', 'ivory', 'ivy', 
'jackpot', 'jaundice', 'jawbreaker', 'jaywalk'
'rhinoceros']

]
